rootProject.name = "2021-12-Java-Developer-Professional-Bulaev"

include("hw01-gradle")
include("hw02-collections")
include("hw03-annotations")
include("hw04-gc")
include("hw05-proxy")
include("hw06-atm")
include("hw07-todo")
include("hw08-io")
include("hw09-jdbc")
include("hw10-jpql")
include("hw11-cache")
include("hw12-webServer")
include("hw13-di")
include("hw14-sprinngboot")
include("hw15-executors")
include("hw16-concurrentCollections")
